[project]
name = "video2mp3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "src/auth",
    "src/gateway",
    "src/converter",
    "src/notification",
]
