[project]
name = "converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jedi>=0.19.2",
    "moviepy>=2.2.1",
    "pika>=1.3.2",
    "pylint>=4.0.2",
    "pymongo>=4.15.3",
]
